title: Reco Arxiv Daily
description: Automatically Update Recommendation ArXiv Papers Daily using Github Actions
show_downloads: true

github:
  zip_url: https://github.com/ShawnBIT/reco-arxiv-daily
  another_url: https://github.com/ShawnBIT/reco-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: ShawnBIT
  url: https://www.wangshen.cc/

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
